### ISSUE TITLE
setq: Symbol’s function definition is void: concatenate

### ISSUE THREAD

**Issue by the42** [dnxbjyj/pasteex-mode#15]
I use GNU Emacs 28.0.92 (build 2, x86_64-w64-mingw32) of 2022-03-27 in TUI-mode on Windows (so started as `emacs -nw`)

I set up pasteex.el as described.

Pasteex helper program is installed and in the path.

If I use the preferred key `C-x p i` the error message is: `setq: Symbol’s function definition is void: concatenate`

**Comment by browneyedape** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yanxin12** [comment]
GNU Emacs 28.0.92 (build 2, x86_64-w64-mingw32)
setq: Symbol’s function definition is void: concatenate 
看了一下el文件，文件里面的concatenate方法显示的是
the function 'concatenate' is not known to defined，不知道怎么解决

**Comment by browneyedape** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by tevig** [comment]
Hello!
Is there a solution to this problem?

**Comment by dnxbjyj** [comment]
fixed at commit [75078b8](https://github.com/dnxbjyj/pasteex-mode/commit/75078b83b66c2f45b59473d3208ea77c30e16ee6)
